# Generated by Django 2.2.10 on 2020-02-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='slod_num',
            new_name='sold_num',
        ),
    ]
