# Generated by Django 2.2.10 on 2020-02-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200215_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='trader_no',
            new_name='trade_no',
        ),
    ]
