# Generated by Django 2.2.10 on 2020-02-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycode',
            old_name='obile',
            new_name='mobile',
        ),
    ]
